"""Königinnenfarbe und Nummer hinzugefügt

Revision ID: 0b9cf75c7ea8
Revises: 3938b01d84db
Create Date: 2025-09-19 22:21:22.042197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b9cf75c7ea8'
down_revision = '3938b01d84db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bee_colony', schema=None) as batch_op:
        batch_op.add_column(sa.Column('queen_color', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('queen_number', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bee_colony', schema=None) as batch_op:
        batch_op.drop_column('queen_number')
        batch_op.drop_column('queen_color')

    # ### end Alembic commands ###
