"""Gesundheitsfeld durch Volksstaerke ersetzt

Revision ID: 3938b01d84db
Revises: b0da2f986ed3
Create Date: 2025-09-17 22:35:08.790364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3938b01d84db'
down_revision = 'b0da2f986ed3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspection', schema=None) as batch_op:
        batch_op.drop_column('health')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('health', sa.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
