"""Neue Felder für Inspektion eingefügt

Revision ID: b0da2f986ed3
Revises: 40e78960445f
Create Date: 2025-09-10 22:23:35.663669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0da2f986ed3'
down_revision = '40e78960445f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mittelwaende', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('brutwaben', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('futterwaben', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('volksstaerke', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sanftmut', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('vitalitaet', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('brut', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('drohnenbrut_geschnitten', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspection', schema=None) as batch_op:
        batch_op.drop_column('drohnenbrut_geschnitten')
        batch_op.drop_column('brut')
        batch_op.drop_column('vitalitaet')
        batch_op.drop_column('sanftmut')
        batch_op.drop_column('volksstaerke')
        batch_op.drop_column('futterwaben')
        batch_op.drop_column('brutwaben')
        batch_op.drop_column('mittelwaende')

    # ### end Alembic commands ###
